# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

x_mashape_key: <%= ENV["x_mashape_key"] %>
google_map_api_key: <%= ENV["google_map_api_key"] %>

development:
  secret_key_base: 67d173c17e52cb98d4c8447321ba4f019fbdce67010988fae2a1d22650954b41a3ef8fd61f4afe4cd7bcc38ceab0ad7b63e146b5095492738e08a184613bd517
  x_mashape_key: <%= ENV["x_mashape_key"] %>
  google_map_api_key: <%= ENV["google_map_api_key"] %>
  
test:
  secret_key_base: 35052044ad6a9c55ec335ca6a9815c6772890a7436ef1fc40bee672f33fe968aa14144e8facd2966b623c7dfec527b86effa35307c1ebdcf5e8bde4976b86d56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  x_mashape_key: <%= ENV["x_mashape_key"] %>
  google_map_api_key: <%= ENV["google_map_api_key"] %>